<%@ page import="java.sql.Date" %><%--
  Created by IntelliJ IDEA.
  User: shiel
  Date: 4/20/2019
  Time: 2:33 PM
  To change this template use File | Settings | File Templates.
  Home page - to-do lists functionality
--%>
<%--To do:
    1) COMPLETE: display a list of tasks with due dates
    2) COMPLETE: update status to complete/incomplete
    3) sort by overdue/not overdue
    4) sort by due in next day/week/month/year
    5) progress bar (percentage of tasks complete for next day/week/month/year
    6) COMPLETE: delete tasks
    7) COMPLETE: default values for new task
    8) CSS
    --%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>The Hub: Home Page</title>
</head>
<body>
<a href="logout.jsp"><h3>Logout</h3></a>       <!-- Logout link -->

<%
    java.sql.Connection conn;                 // Connection: A connection with a specific database.
    java.sql.ResultSet rs;                   // ResultSet: A table of data representing a database result set, which is usually generated by executing a statement that queries the database.
    java.sql.ResultSet rs1;
    java.sql.Statement st;                   // Statement: The object used for executing a static SQL statement and returning the results it produces.
    java.sql.Statement st1;                   // Statement: The object used for executing a static SQL statement and returning the results it produces.
    // mysql database to work with your project. Go to,
    // Your project -> right click -> properties -> Libraries -> Compiler tab -> Add library -> select "MySQL JDBC Driver" library -> Ok
    Class.forName("com.mysql.jdbc.Driver"); //to connect mysql database
    conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/thehub", "root", "2342");  //connection with database.. demo: db name, username:root, password: " "
    st = conn.createStatement();
    st1 = conn.createStatement();
    String qr;
    int user_id = -1;

    if (session.getAttribute("uname") == null) {
        response.sendRedirect("loginAndSignup.jsp");
    }

    //check if session we created exists or not
    else if (session.getAttribute("uname") != null) {
        qr = "SELECT user_id FROM users WHERE username = '" + session.getAttribute("uname") + "';";
        rs = st.executeQuery(qr);
        if (rs.next()) {
            user_id = rs.getInt("user_id");
        }
        rs.close();

        qr = "SELECT * FROM todo WHERE user_id = " + user_id + ";";
        rs = st.executeQuery(qr);
%>

<div>
    <%--//__________________________________________________________________________________________--%>
    <%--//__________________________________________________________________________________________--%>
    <%--Display all uncompleted tasks--%>
    <%--//__________________________________________________________________________________________--%>
    <%--//__________________________________________________________________________________________--%>
    <table style="float: left; border: 1px solid black; width:30%;">
        <tbody>
        <tr>
            <th>To-do List</th>
        </tr>
        <form name="markComplete" Method="POST">
            <%
                while (rs.next()) {
                    if (rs.getInt("is_completed") != 1) {
                        int todo_id = rs.getInt("todo_id");
            %>
            <%--    hidden input to get all of the user's todo_ids--%>
            <input type="hidden" name="todo_ids" value="<%=todo_id%>"/>
            <br/>
            <tr>
                <td>
                    <table border="2">
                        <tbody>
                        <tr>
                            <th><%=rs.getString("task_name")%>
                            </th>
                        </tr>
                        <tr>
                            <td><%=rs.getString("text_data")%>
                            </td>
                            <td>
                                <%--                mark each box with specific todo_id to pass to markAsComplete handler--%>
                                <input type="checkbox" name="complete<%=todo_id%>" value="complete"/>
                            </td>
                        </tr>
                        <tr>
                            <%
                                java.sql.Date due = rs.getDate("due_date");
                                if (due == null) {
                            %>
                            <td>No Due Date
                            </td>
                            <%
                            } else {
                            %>
                            <td>Due Date: <%=due%>
                            </td>
                            <%
                                }
                            %>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <%
                    }
                }
            %>
            <br/>
            <tr>
                <td>
                    <input type="submit" name="markChecked" value="Mark Selected Tasks as Complete"/> <br/>
                    <input type="submit" name="deleteTasks" value="Delete Selected Tasks"/>
                </td>
            </tr>
        </form>
        </tbody>
    </table>


    <%--//__________________________________________________________________________________________--%>
    <%--//__________________________________________________________________________________________--%>
    <%--Display all completed tasks--%>
    <%--//__________________________________________________________________________________________--%>
    <%--//__________________________________________________________________________________________--%>
    <%
        rs.close();
        qr = "SELECT * FROM todo WHERE user_id = " + user_id + ";";
        rs = st.executeQuery(qr);
    %>
    <table style="float: left; border: 1px solid black; width:30%;">
        <tbody>
        <tr>
            <th>Completed Tasks</th>
        </tr>
        <form name="markInomplete" Method="POST">
            <%
                while (rs.next()) {
                    if (rs.getInt("is_completed") == 1) {
                        int todo_id = rs.getInt("todo_id");
            %>
            <%--    hidden input to get all of the user's todo_ids--%>
            <input type="hidden" name="todo_ids" value="<%=todo_id%>"/>
            <br/>
            <tr>
                <td>
                    <table border="2">
                        <tbody>
                        <tr>
                            <th><%=rs.getString("task_name")%>
                            </th>
                        </tr>
                        <tr>
                            <td><%=rs.getString("text_data")%>
                            </td>
                            <td>
                                <%--                mark each box with specific todo_id to pass to markAsComplete handler--%>
                                <input type="checkbox" name="complete<%=todo_id%>" value="incomplete"/>
                            </td>
                        </tr>
                        <tr>
                            <%
                                java.sql.Date due = rs.getDate("due_date");
                                if (due == null) {
                            %>
                            <td>No Due Date
                            </td>
                            <%
                            } else {
                            %>
                            <td>Due Date: <%=due%>
                            </td>
                            <%
                                }
                            %>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <%
                    }
                }
            %>
            <br/>
            <tr>
                <td>
                    <input type="submit" name="markCheckedIn" value="Mark Selected Tasks as Incomplete"/> <br/>
                    <input type="submit" name="deleteTasks" value="Delete Selected Tasks"/>
                </td>
            </tr>
        </form>
        </tbody>
    </table>
    <%--//__________________________________________________________________________________________--%>
    <%--//__________________________________________________________________________________________--%>
    <%--provide option to create tasks--%>
    <%--//__________________________________________________________________________________________--%>
    <%--//__________________________________________________________________________________________--%>
    <br/>
</div>


<form name="createTask" method="POST">
    <input type="submit" name="makeTask" value="Create a new task"/>
</form>

<%
    //create a form to input a new task
    if (request.getParameter("makeTask") != null) {
%>
<form name="taskForm" method="POST">
    Task Name: <input type="text" name="taskName"> <br/>
    Task Description: <input type="text" name="taskDescription"> <br/>
    Due Date: <input type="date" name="dueDate"> <br/>
    <input type="submit" name="finalizeCreation" value="Make Task">
</form>
<%
    }
    //if user decides to create a task, set session attributes and navigate to NewTask.jsp
    if (request.getParameter("finalizeCreation") != null) {
        session.setAttribute("dueDate", request.getParameter("dueDate"));
        session.setAttribute("taskName", request.getParameter("taskName"));
        session.setAttribute("taskDescription", request.getParameter("taskDescription"));
        response.sendRedirect("NewTask.jsp?user_id=" + user_id);
    }

    //__________________________________________________________________________________________
    //__________________________________________________________________________________________
    //if user decides to delete task, send todo_id to DeleteTask.jsp
    //__________________________________________________________________________________________
    //__________________________________________________________________________________________

    if (request.getParameter("deleteTasks") != null) {
        String[] todo_ids = request.getParameterValues("todo_ids");
%>
<form name="toDelete" method="POST" action="DeleteTask.jsp"><%
    for (String id : todo_ids) {
        String temp = request.getParameter("complete" + id);
        if (temp != null) {
%>
    <input type="hidden" name="thingsToDelete" value="<%=id%>"/>
    <%
            }
        }%>
    Are you sure you want to delete the selected tasks? <br/>
    <input type="submit" name="sure" value="Continue">
    <input type="submit" name="sure" value="Cancel">
</form>
<%

    }

    //__________________________________________________________________________________________
    //__________________________________________________________________________________________
    //if user decides to mark task as complete, send todo_id to MarkAsComplete.jsp
    //__________________________________________________________________________________________
    //__________________________________________________________________________________________
    if (request.getParameter("markChecked") != null) {
        String[] todo_ids = request.getParameterValues("todo_ids");
%>
<form name="toMark" method="POST" action="MarkAsComplete.jsp"><%
    for (String id : todo_ids) {
        String temp = request.getParameter("complete" + id);
        if (temp != null) {
%>
    <input type="hidden" name="markAsDone" value="<%=id%>"/>
    <%
            }
        }%>
    Are you sure you want to mark the selected tasks as complete? <br/>
    <input type="submit" name="sure" value="Continue">
    <input type="submit" name="sure" value="Cancel">
</form>
<%
    }

    //__________________________________________________________________________________________
    //__________________________________________________________________________________________
    //if user decides to mark task as incomplete, send todo_id to MarkAsIncomplete.jsp
    //__________________________________________________________________________________________
    //__________________________________________________________________________________________
    if (request.getParameter("markCheckedIn") != null) {
        String[] todo_ids = request.getParameterValues("todo_ids");
%>
<form name="toMarkIn" method="POST" action="MarkAsIncomplete.jsp"><%
    for (String id : todo_ids) {
        String temp = request.getParameter("complete" + id);
        if (temp != null) {
%>
    <input type="hidden" name="markAsUndone" value="<%=id%>"/>
    <%
            }
        }%>
    Are you sure you want to mark the selected tasks as incomplete? <br/>
    <input type="submit" name="sure" value="Continue">
    <input type="submit" name="sure" value="Cancel">
</form>
<%
        }

    }
%>
</body>
</html>
