<%-- 
    Document   : signupprocess
    Created on : 04/17/2019
    Author     : Aidan Lambrecht, taken from Abishek's examples
--%>
<%
    java.sql.Connection conn;                 // Connection: A connection with a specific database.
    java.sql.ResultSet rs;                   // ResultSet: A table of data representing a database result set, which is usually generated by executing a statement that queries the database. 
    java.sql.Statement st,st1;               // Statement: The object used for executing a static SQL statement and returning the results it produces.
    // mysql database to work with your project. Go to,
    // Your project -> right click -> properties -> Libraries -> Compiler tab -> Add library -> select "MySQL JDBC Driver" library -> Ok
    Class.forName("com.mysql.jdbc.Driver"); //to connect mysql database
    conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/thehub", "root", "2342");  //connection with database.. demo: db name, username:root, password: " "
    st = conn.createStatement();
    st1 = conn.createStatement();

    //get parameter value by using the 'name' of the field
    String firstname = request.getParameter("firstname");   
    String lastname = request.getParameter("lastname");     
    String username = request.getParameter("username");     
    String password = request.getParameter("password");

    String qr = "SELECT username FROM users WHERE username = '"+username+"'";    //query to select if the username already exists or not
    rs = st.executeQuery(qr);
    if(rs.next())                       
    {
        // passing variable "a" with URL
        // lets say "a" is for "user already exists"
        response.sendRedirect("loginAndSignup.jsp?a");                                    // if username found in database, redirect user to loginAndSignup.jsp with some error
    }
    else
    {
        String sql = "INSERT INTO thehub.users (fname, lname, username, password, is_shown) VALUES ('"+firstname+"', '"+lastname+"', '"+username+"', '"+password+"', 0)";   //query to enter values in database
        st1.executeUpdate(sql);
        //create session: to keep track of user
        // we will check on index.jsp if this session was created or not.
        // if not user must login to go to index.jsp
        session.setAttribute("uname", username);          //session created... name: 'uname' and value: 'username' of the user    
        response.sendRedirect("index.jsp");
    }
%>